### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "Tyr Chen",
    "email": "tchen@acme.org",
    "password": "123456"
}

### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "Alice Chen",
    "email": "alice@acme.org",
    "password": "123456"
}

### signin user (valid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "tchen@acme.org",
    "password": "123456"
}

### signin user (invalid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "alice@acme.org",
    "password": "123456"
}


### signin user (invalid)

# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "tchen@acme.org",
    "password": "123456"
}

@token = {{signin.response.body.token}}


### get chat list
GET http://localhost:6688/api/chat
Authorization: Bearer {{token}}



### get user list

GET http://localhost:6688/api/users
Authorization: Bearer {{token}}


### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "LG",
    "fullname": "hyx",
    "email": "hyx@lg.com",
    "password": "123456"
}

### signin user (invalid)

# @name signin_hyx
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "hyx@lg.com",
    "password": "123456"
}

@token_hyx = {{signin_hyx.response.body.token}}

### create chat

# @name create_chat
POST http://localhost:6688/api/chats
Authorization: Bearer {{token_hyx}}
Content-Type: application/json

{
    "name": "test",
    "members": [1, 2],
    "public": true
}

@chat_id = {{create_chat.response.body.id}}

### get chat

GET http://localhost:6688/api/chats/{{chat_id}}
Authorization: Bearer {{token_hyx}}


### get all chat

GET http://localhost:6688/api/chats
Authorization: Bearer {{token_hyx}}

### update chat

PATCH http://localhost:6688/api/chats/{{chat_id}}
Authorization: Bearer {{token_hyx}}
Content-Type: application/json

{
    "name": "test_update"
}

### delete chat

DELETE http://localhost:6688/api/chats/{{chat_id}}
Authorization: Bearer {{token_hyx}}


GET http://localhost:6688/api/users
Authorization: Bearer {{token}}


### upload files

POST http://localhost:6688/api/upload
Authorization: Bearer {{token_hyx}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="test.jpg"
Content-Type: application/octet-stream

< D:\picture\test.jpg
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--


### get files

GET http://localhost:6688/api/files/2/096/045/e981f7c375b603d5e18f7df3417ab1ee10.jpg
Authorization: Bearer {{token_hyx}}
